order add 구현
wecode-bootcamp-korea/38-1st-WESH-Korea-backend pull request #10
Opened 2022-10-22 12:03 UTC by dnrdls7

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 결제 기능 중 주문 접수 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 주문 접수 기능
- 상품 상세페이지의 바로구매, 장바구니에서 상품 복수 체크 후 구매를 주문 접수 할 수 있는 기능 구현
- 상세페이지에서 구매 : input = 객체 product_info / key = product_id, product_price, product_quantity
- 장바구니에서 복수 체크 후 구매 : input = 객체 product_info / key = product_id, product_price, product_quantity로 구성된 배열
- orders table에 주문 유저를 저장하고 status 1을 부여 (status 1 = 결제완료 상태 코드)
- order_items table에 주문한 상품 or 상품들 을 저장
- 장바구니에서 구매 했을 경우 장바구니 목록에서 주문 상품들을 제거 (cart 기능 merge 전이라 주석처리)
- 총 결제 금액만큼 user point에서 차감

2. 에러 응답
- product_info 입력값이 없을 때 = KEY_ERROR
- product_info 값이 비었거나, 빈 배열일 때 = ORDER_PRODUCT_IS_NOT_VALID
- product_info 의 product_quantity 값이 숫자가 아닐 때 = QUANTITY_IS_NOT_NUMBER
- product_info 의 product_quantity 값이 유효하지 않은 비지니스로직 (제한 구매 수량 초과or미만) 일 때 = QUANTITY_IS_NOT_VALID

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 하나의 기능에 연관되어 있는 table 수가 많아지고, 기능 수행에서 장바구니 목록을 삭제해야 하는 등 구현되어 있는 다른 함수들을 사용하는 등 복잡한 구성을 다뤄볼 수 있어서 좋았습니다.

<br />

## :: 기타 질문 및 특이 사항
- order_statuses table의 존재 의미는 이해하였으나, order_item_statuses table의 의미를 제대로 이해하지 못 하였습니다.
- 기능을 구현하기 전에 팀원들과의 의견에서는 구매한 상품들의 대한 상태로 인지하여, 품절, 재입고중, 판매중, 재고 적음(품절 임박) 등으로 생각했었습니다.
- 기능을 구현하면서 든 생각은 해당 status들은 products table에 stock으로 표현이 가능해보이며, 품절 등의 상태는 상품 stock에 따라 자동적으로 부여 될 수 있는 tag같은 것으로 구현하는게 맞다는 생각이 들었습니다.
- order_item_statuses의 정확한 존재 의미가 궁금합니다.

2022-10-26 13:59 UTC, dnrdls7 commented
##구현 기능
 1. 구매 확정 기능 구현
   - 구매 확정 시 order status를 confirmation_of_order로 변경
   - 구매 확정 시 구매한 총 금액의 2%를 마일리지(포인트)로 지급
 2. 주문 취소 & 환불 기능 구현
   - order cancel 요청 시 현재 order status를 확인하여, 배송 이전 이라면 100% 환불 처리되고, order의 status를 withdraw_order로 변경함
   - 배송 이후라면 결제 금액에서 배송비 *2 만큼 차감하여 환불을 진행하고, order의 status를 refund로 변경함

2022-10-27 08:17 UTC, kyeongraekim requested changes

2022-10-27 08:17 UTC, kyeongraekim commented on api/models/orderDao.js
> +    [ user_id, 1 ]
다음의 예시 코드와 같은 내용을 models/enums.js 파일에 생성 및 활용하여, 숫자를 직접 기입하는 하드코딩이 아닌 해당 id값을 치환할 수 있는 글자용어로 수정해주세요.

```javascript

const orderStatusEnum = Object.freeze({
    CART : 1,
    ORDER : 2,
    DONE : 3
})

module.exports ={
    orderStatusEnum
}

2022-10-27 08:17 UTC, kyeongraekim commented on api/models/orderDao.js
> +    [ user_id, 1 ]
enum의 역할과 기능을 잘 소개한 블로그 글 링크를 아래 남겨드립니다.
[링크 바로가기](https://sewonzzang.tistory.com/28)

2022-10-27 08:17 UTC, kyeongraekim commented on api/services/orderService.js
> +  const SHIPPING_FEE = 2500;
해당 ID 값들도 위 enum 관련 내용 참고하여서 리팩토링해주세요~

2022-10-27 08:59 UTC, kyeongraekim requested changes

2022-10-27 08:59 UTC, kyeongraekim commented on api/models/enums.js
> +  CONFIRMATION_ORDER_STATUS_ID : 6,
orderStatus 에 해당되어 실제 DM에서 id값으로 관리하는 내용이 들어가야합니다. 이곳보다 아래에 위치한 Quantity_Lower_Limit 등은 이곳에는 들어와서는 안되는 내용으로 보여지네요!~

2022-10-28 07:36 UTC, merged