Get product info
wecode-bootcamp-korea/38-1st-WESH-Korea-backend pull request #13
Opened 2022-10-24 15:30 UTC by tlacodnjs667

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
프로덕트 리스트 구현 (카테고리별 필터링 & 재정렬) 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 리스트 구현 
- 상품별 이름, 가격, 이미지, 카테고리명 등 상품 관련 정보 프론트에 전달
2. 카테고리별 상품 필터링
- 카테고리명을 프론트에서 path 파라미터를 통해 전달받아 해당하는 id 값을 통해 제품 필터링해 해당 카테고리별 상품 정보 프론트에 전달
3. 상품 재정렬 기능
- 가격 오름차순, 내림차순, 인기순(판매량), 리뷰많은순 등 4가지로 구분하여 재정렬 기능 구현
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 현재 상황에서 차선책을 선택할 수 있는 방법을 고안할 수 있게 됨.
- 스스로 부족한 점에 대해 깨달음.
- 우선 TRELLO 등 다른 팀원들과 정보를 기록해가며 협업할 수 있는 툴들에 취약하다는 점을 알게됨.
- 우선 순위와 무엇을 할 때, 어떤 구성으로 실행할 것인지 확인하는 습관을 들여야 할 듯 싶음
- 스스로 구글링하는 방법을 알게되었으면 함.
- 시간을 조절하는 방식에 대한 스스로의 정의가 필요한 것 같음

<br />

## :: 기타 질문 및 특이 사항
- 현재 Switch 문 등 코드가 길어지는 것이 문제이고, 그리고 리팩토링을 하고 싶은데 어떤 방식으로 할 수 있을지 고민이 됩니다.

2022-10-25 03:06 UTC, kyeongraekim requested changes

2022-10-25 03:06 UTC, kyeongraekim commented on api/models/productDao.js
> +};
해당 모듈은 user_product 사이에 있는 모든 데이터를 세는 기능으로 보여지네요! 판매량을 세는 로직으로 보여지지는 않아보이는데 한 번 고민해주세요!

2022-10-25 03:06 UTC, kyeongraekim commented on api/models/productDao.js
> +LIMIT ? OFFSET ?;
- 가독성을 위해서 쿼리문의 indentation을 한 번 신경써주세요!

2022-10-25 07:20 UTC, tlacodnjs667 commented on api/models/productDao.js
> +LIMIT ? OFFSET ?;
넵~

2022-10-27 06:31 UTC, kyeongraekim requested changes

2022-10-27 06:31 UTC, kyeongraekim commented on api/services/userService.js
> +		const error = new Error('KEY_ERROR__MMO')
MMO의 의미가 불분명하네요!

2022-10-27 06:31 UTC, kyeongraekim commented on api/services/productService.js
> +    result[i].tag = tagArr;
웹 개발시 i, j 와 같은 분명하지 않은 변수명 사용은 지양해주세요! 구체적으로 각 내용이 지닐 수 있는 별칭을 고민해주세요!~

2022-10-27 07:30 UTC, kyeongraekim approved these changes
LGTM!~

2022-10-27 07:30 UTC, merged