[ADD]이벤트 상품 리뷰
wecode-bootcamp-korea/38-1st-WESH-Korea-backend pull request #18
Opened 2022-10-25 14:03 UTC by Hey-Hello-World

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 이벤트 페이지 리뷰 CRUD 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 이벤트 페이지 리뷰 작성하기
- 중복 작성 불가능 로직 구현
2. 리뷰 수정하기
- 해당 리뷰 작성자만 수정 가능
3. 리뷰 삭제하기
- 해당 리뷰 작성자만 삭제 가능

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-10-26 08:10 UTC, kyeongraekim requested changes

2022-10-26 08:10 UTC, kyeongraekim commented on api/controllers/eventCommentController.js
> +    const evReviewId = +req.params.evTitleId;
- 영어 약어사용을 지양하고 영어 원어를 꼭 풀어서 써주세요~. 비효율적인 결과를 낼 수 있는, 먼 미래에 레거시가 될 가능성이 높은 변수명으로 보여집니다.

2022-10-26 08:10 UTC, kyeongraekim commented on api/services/eventCommentService.js
> +        const error = new Error("YOU_ALREADY_WROTE_THIS_REVIEW");
- 에러메세지는 사용자가 보는 메세지가아닌, 프론트엔드/클라이언트 그리고 백엔드 내부적으로 확인하는 메세지입니다. 따라서 사용자에게 전달될 법한 메세지가 아닌 Duplicated Entry 정도로 에러 핸들링의 표지판 역할을 할 수 있는 메세지로 바꾸어주세요!~

2022-10-26 08:10 UTC, kyeongraekim commented on api/services/eventCommentService.js
> +        const error = new Error("YOU_DIDN'T_WRITE_THIS_REVIEW");
에러메세지는 사용자가 보는 메세지가아닌, 프론트엔드/클라이언트 그리고 백엔드 내부적으로 확인하는 메세지입니다. 따라서 사용자에게 전달될 법한 메세지가 아닌 Duplicated Entry 정도로 에러 핸들링의 표지판 역할을 할 수 있는 메세지로 바꾸어주세요!~

2022-10-26 08:28 UTC, Hey-Hello-World commented on api/controllers/eventCommentController.js
> +    const evReviewId = +req.params.evTitleId;
감사합니다 수정 완료 하였습니다.

2022-10-26 08:28 UTC, Hey-Hello-World commented on api/services/eventCommentService.js
> +        const error = new Error("YOU_ALREADY_WROTE_THIS_REVIEW");
감사합니다 수정완료 하였습니다.

2022-10-26 08:29 UTC, Hey-Hello-World commented on api/services/eventCommentService.js
> +        const error = new Error("YOU_DIDN'T_WRITE_THIS_REVIEW");
감사합니다 수정 완료하였습니다.

2022-10-26 08:43 UTC, kyeongraekim requested changes

2022-10-26 08:43 UTC, kyeongraekim commented on api/services/eventCommentService.js
> +        const error = new Error("NO_PERMISSION");
- 권한 없음에 해당되는 401 상태코드로 수정해주세요!~

2022-10-26 11:05 UTC, Hey-Hello-World commented on api/services/eventCommentService.js
> +        const error = new Error("NO_PERMISSION");
경래 멘토님께서 언급해주신 덕분에 에러코드 공부도 다시 보게 되었습니다  감사합니다. 수정 완료 하였습니다.

2022-10-27 02:01 UTC, kyeongraekim approved these changes
LGTM!~

2022-10-27 02:02 UTC, merged